### PR TITLE
Update Browse

### LINKED ISSUE #6: Update Browse page
Update Browse page to reflect style/structure of Home.

### PR DESCRIPTION
**Pull request by digilou**
Closes #6 

- New header, nav, and footer added (style consistency)
- `</br>` replaced with `<br>` (HTML correction)
- `target="blank"` removed, and "external link" provided at end of text (usability update)
- inline styled `<p>`s replaced with `<hr>`s
- Copy summed up.
- Search result placeholder text added

QA:
- [ ] Text successfully displays
- [ ] Browse results successfully pull in

### CODE REVIEW

**Comment by ddcornwall** [comment]
Reviewing the code it looks like clicking on links will open in the same window. While I understand where you are coming from, I'm uncomfortable with that change. At this stage, if we have the user view a result in the same window and then click the back button, the search will re-execute. Some of the searches are time consuming for factors currently beyond our control. I think this would be a frustrating experience for more users. 

I am open to ideas about how to fix it so that the search doesn't reexecute upon hitting the back button. Some kind of "return to results" link. 

I'll also verify my suspicions by actually testing the code tonight or tomorrow. Time constraints keep me from doing it now.

**Comment by ddcornwall** [comment]
Also, everything else looked fine.

**Comment by digilou** [comment]
@ddcornwall It looks like Safari is the only one that preserves the results. Firefox and Chrome back button returns you to a clean slate without recent search results. Considering that code has to be revised to fix that, I'll return `target=_blank`.

It's only in the past year I've felt strongly about this due to the articles I've read. It is disorienting for screen readers, but can also be disorienting for others users, dependent upon their browser's default behavior and user expectations (which varies).

**Comment by digilou** [comment]
Something else to consider when opening in a new window/tab:
https://developers.google.com/web/tools/lighthouse/audits/noopener
I've added `rel="no opener"` to couple with `target="_blank"` per Google's recommendation.

**Pull request merged**
