### PR TITLE
update global nav; refine search box

### LINKED ISSUE #14: Update global nav
Make Home, Browse, and About primary nav. Move Github and Bug Reports to secondary (from footer).

### PR DESCRIPTION
**Pull request by digilou**
Closes #14 

- Transferred Home, Browse, About to primary global nav
- Moved View on Github and Report a Bug from footer to secondary global nav
- Updated semantics and styling of primary search form
- Setup placeholder for Bio page in footer

QA:
- [ ] Home page appears
- [ ] Primary global nav takes on USWDS styling
- [ ] Mobile nav is collapsible
- [ ] Search form works and results display

### CODE REVIEW

**Comment by ddcornwall** [comment]
@digilou I think I might have messed up the merge. I'm not seeing the new nav on browse or about. Could you have a second look. Apologies if I somehow overwrote your work.

**Comment by digilou** [comment]
@ddcornwall Sorry! Maybe unclear. New nav on Home reflecting links to sub pages. You did fine!

**Comment by digilou** [comment]
I'll update the Browse and About pages once I'm satisfied with Home nav, since it's all copy and paste. No include feature here unless we move to a server-side programming language like Node.

**Comment by ddcornwall** [comment]
Thanks. With your comments it's clear I read the request wrong. I'm putting it down to making an airport run at 3:45am.

**Comment by ddcornwall** [comment]
I do like the new navigation!

**Pull request merged**
